# Generated by Django 6.1 on 2026-08-11 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0003_alter_expense_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="expense",
            name="include_in_profit",
            field=models.BooleanField(
                default=True,
                help_text="Include this expense in business profit calculation.",
            ),
        ),
    ]
