# Generated by Django 6.1 on 2026-08-11 04:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("master_data", "0008_material"),
    ]

    operations = [
        migrations.CreateModel(
            name="Labour",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("mobile", models.CharField(blank=True, max_length=15)),
                ("joining_date", models.DateField(blank=True, null=True)),
                (
                    "payment_basis",
                    models.CharField(
                        choices=[("DAILY", "Daily"), ("MONTHLY", "Monthly")],
                        max_length=10,
                    ),
                ),
                (
                    "rate",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("ACTIVE", "Active"), ("INACTIVE", "Inactive")],
                        default="ACTIVE",
                        max_length=10,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "labour_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="labour_members",
                        to="master_data.labourtype",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
