# Generated by Django 6.1 on 2026-08-11 04:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("labour", "0001_initial"),
        ("master_data", "0008_material"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="labour",
            name="labour_type",
        ),
        migrations.RemoveField(
            model_name="labour",
            name="payment_basis",
        ),
        migrations.RemoveField(
            model_name="labour",
            name="rate",
        ),
        migrations.CreateModel(
            name="LabourTypeAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "payment_basis",
                    models.CharField(
                        choices=[("DAILY", "Daily"), ("MONTHLY", "Monthly")],
                        max_length=10,
                    ),
                ),
                (
                    "rate",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("effective_from", models.DateField()),
                ("effective_to", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "labour",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="type_assignments",
                        to="labour.labour",
                    ),
                ),
                (
                    "labour_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assignments",
                        to="master_data.labourtype",
                    ),
                ),
            ],
            options={
                "ordering": ["-effective_from"],
            },
        ),
    ]
