# Generated by Django 6.1 on 2026-08-11 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("labour", "0002_remove_labour_labour_type_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="labourtypeassignment",
            name="rate",
        ),
    ]
