# Generated by Django 6.1 on 2026-08-11 05:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("labour", "0003_remove_labourtypeassignment_rate"),
    ]

    operations = [
        migrations.CreateModel(
            name="LabourEarning",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "earning_type",
                    models.CharField(
                        choices=[
                            ("DAILY_WAGE", "Daily Wage"),
                            ("MONTHLY_SALARY", "Monthly Salary"),
                        ],
                        max_length=20,
                    ),
                ),
                ("earning_date", models.DateField()),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "labour",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="earnings",
                        to="labour.labour",
                    ),
                ),
            ],
            options={
                "ordering": ["-earning_date"],
            },
        ),
    ]
