# Generated by Django 6.1 on 2026-08-11 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("labour", "0005_labourpayment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="labourtypeassignment",
            name="effective_from",
            field=models.DateField(blank=True, null=True),
        ),
    ]
