# Generated by Django 6.1 on 2026-08-11 05:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("labour", "0006_alter_labourtypeassignment_effective_from"),
    ]

    operations = [
        migrations.CreateModel(
            name="LabourSalaryPeriod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.PositiveIntegerField()),
                ("month", models.PositiveSmallIntegerField()),
                ("salary_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "status",
                    models.CharField(
                        choices=[("OPEN", "Open"), ("SETTLED", "Settled")],
                        default="OPEN",
                        max_length=10,
                    ),
                ),
                ("settled_at", models.DateTimeField(blank=True, null=True)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "labour",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="salary_periods",
                        to="labour.labour",
                    ),
                ),
            ],
            options={
                "ordering": ["-year", "-month"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("labour", "year", "month"),
                        name="unique_labour_salary_period",
                    )
                ],
            },
        ),
    ]
