# Generated by Django 6.1 on 2026-08-29 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("labour", "0007_laboursalaryperiod"),
    ]

    operations = [
        migrations.AddField(
            model_name="labour",
            name="is_driver",
            field=models.BooleanField(
                default=False, help_text="Mark if this labour also gets Driver Payment"
            ),
        ),
        migrations.CreateModel(
            name="LabourDriverPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("note", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "labour",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="driver_payments",
                        to="labour.labour",
                    ),
                ),
            ],
            options={
                "ordering": ["-period_end", "-id"],
            },
        ),
        migrations.CreateModel(
            name="LabourExtraPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("note", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "labour",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="extra_payments",
                        to="labour.labour",
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "-id"],
            },
        ),
        migrations.CreateModel(
            name="LabourOldBalance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "labour",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="old_balance",
                        to="labour.labour",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LabourSettlement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("settlement_date", models.DateField()),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                (
                    "total_salary",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Trip shares + extras + driver payment",
                        max_digits=12,
                    ),
                ),
                (
                    "total_advance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "net_payable",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="total_salary - total_advance",
                        max_digits=12,
                    ),
                ),
                (
                    "old_balance_before",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "old_balance_deducted",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "cash_paid",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "final_old_balance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("note", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "labour",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="settlements",
                        to="labour.labour",
                    ),
                ),
            ],
            options={
                "ordering": ["-settlement_date", "-id"],
            },
        ),
        migrations.CreateModel(
            name="LabourTripGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("trip_count", models.PositiveIntegerField()),
                (
                    "rate_per_trip",
                    models.DecimalField(
                        decimal_places=2,
                        default=450,
                        help_text="Per-trip rate (default ₹450)",
                        max_digits=10,
                    ),
                ),
                (
                    "fill_type",
                    models.CharField(
                        choices=[("HAND", "Hand"), ("JCB", "JCB")],
                        default="HAND",
                        max_length=10,
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2, editable=False, max_digits=12
                    ),
                ),
                ("note", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "labourers",
                    models.ManyToManyField(
                        related_name="trip_groups", to="labour.labour"
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "-id"],
            },
        ),
        migrations.CreateModel(
            name="LabourAdvance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("note", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "labour",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="advances",
                        to="labour.labour",
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "-id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("labour", "date"),
                        name="unique_advance_per_labour_per_day",
                    )
                ],
            },
        ),
    ]
