# Generated by Django 6.1 on 2026-08-31 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("labour", "0008_labour_is_driver_labourdriverpayment_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="labour",
            name="category",
            field=models.CharField(
                choices=[
                    ("TRACTOR_DRIVER", "Tractor Driver"),
                    ("HYVA_DRIVER", "Hyva Driver"),
                    ("JCB_OPERATOR", "JCB Operator"),
                    ("MISTRI", "Mistri"),
                    ("LABOUR", "Labour"),
                ],
                default="LABOUR",
                help_text="Worker category — Tractor Driver, Hyva Driver, JCB Operator, Mistri or Labour",
                max_length=30,
            ),
        ),
    ]
