# Generated by Django 6.1 on 2026-08-31 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("labour", "0009_labour_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="labour",
            name="category",
            field=models.CharField(
                choices=[
                    ("TRACTOR", "Tractor"),
                    ("HYVA_DRIVER", "Hyva Driver"),
                    ("JCB_OPERATOR", "JCB Operator"),
                    ("MISTRI", "Mistri"),
                ],
                default="TRACTOR",
                help_text="Worker category — Tractor (driver+labour), Hyva Driver, JCB Operator or Mistri (incl. labour)",
                max_length=30,
            ),
        ),
    ]
