# Generated by Django 6.1 on 2026-08-31 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("labour", "0011_convert_category_values"),
    ]

    operations = [
        migrations.AddField(
            model_name="labourtripgroup",
            name="load_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "— (Generic trip)"),
                    ("WHITE_HYVA", "White Sand Hyva"),
                    ("FLYASH_HYVA", "Fly Ash Hyva"),
                    ("HALFTON_WHITE", "Halfton White"),
                    ("HALFTON_FLYASH", "Halfton Fly Ash"),
                ],
                default="",
                help_text="Hyva load type — sets the per-trip rate automatically",
                max_length=20,
            ),
        ),
    ]
