# Generated by Django 6.1 on 2026-08-31 10:23

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("labour", "0012_labourtripgroup_load_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="labour",
            name="base_daily_rate",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("500"),
                help_text="Base daily rate (Rozi full day). One & Half = 1.5x, Half = 0.5x",
                max_digits=10,
            ),
        ),
        migrations.CreateModel(
            name="LabourRozi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "day_type",
                    models.CharField(
                        choices=[
                            ("FULL", "Full Day"),
                            ("ONE_HALF", "One & Half Day"),
                            ("HALF", "Half Day"),
                        ],
                        default="FULL",
                        max_length=10,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("note", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "labour",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rozis",
                        to="labour.labour",
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "-id"],
            },
        ),
    ]
