# Generated by Django 6.1 on 2026-08-31 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("labour", "0013_labour_base_daily_rate_labourrozi"),
    ]

    operations = [
        migrations.AddField(
            model_name="labour",
            name="sub_category",
            field=models.CharField(
                blank=True,
                choices=[("MISTRI", "Mistri"), ("HELPER", "Mistri Helper (Labour)")],
                default="",
                help_text="For Mistri category — Mistri (fixed ₹800/day) or Mistri Helper/Labour (variable base rate)",
                max_length=20,
            ),
        ),
    ]
