# Generated by Django 6.1 on 2026-09-02 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("labour", "0014_labour_sub_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="labour",
            name="is_vendor",
            field=models.BooleanField(
                default=False,
                help_text="Auto-created placeholder for a vendor's own driver (<Customer> Driver). Hidden from daily labour lists so no advances/payments are tracked for it.",
            ),
        ),
        migrations.AlterField(
            model_name="labourtripgroup",
            name="load_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "— (Tractor trip)"),
                    ("WHITE_HYVA", "White Sand Hyva"),
                    ("FLYASH_HYVA", "Fly Ash Hyva"),
                    ("HALFTON_WHITE", "Halfton White"),
                    ("HALFTON_FLYASH", "Halfton Fly Ash"),
                ],
                default="",
                help_text="Hyva load type — sets the per-trip rate automatically",
                max_length=20,
            ),
        ),
    ]
