# Generated by Django 6.1 on 2026-09-02 10:38

from django.db import migrations


def flag_existing_vendor_drivers(apps, schema_editor):
    """Auto-created '<Customer> Driver' placeholders ko is_vendor=True mark karo.

    Vendor trips par '<Customer> Driver' naam ka HYVA_DRIVER Labour seed hota
    hai (trips.views._ensure_vendor_driver). Wo regular Hyva Driver section,
    advances aur payments se hidden hona chahiye. Name wala pattern (ends with
    ' Driver') real drivers (Dinesh Bhaiya, Gaju Bhau, ...) ko match nahi karta.
    """
    Labour = apps.get_model('labour', 'Labour')
    updated = Labour.objects.filter(name__iendswith='Driver').update(is_vendor=True)
    print(f'  flagged {updated} vendor driver placeholder(s)')


def reverse_flag(apps, schema_editor):
    Labour = apps.get_model('labour', 'Labour')
    Labour.objects.filter(name__iendswith='Driver').update(is_vendor=False)


class Migration(migrations.Migration):

    dependencies = [
        ("labour", "0015_labour_is_vendor_alter_labourtripgroup_load_type"),
    ]

    operations = [
        migrations.RunPython(flag_existing_vendor_drivers, reverse_flag),
    ]
