# Generated by Django 6.1 on 2026-09-07 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("labour", "0016_flag_vendor_drivers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="labourtripgroup",
            name="load_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "— (Tractor trip)"),
                    ("WHITE_HYVA", "White Sand Hyva"),
                    ("FLYASH_HYVA", "Fly Ash Hyva"),
                    ("HALFTON_WHITE", "Halfton White"),
                    ("HALFTON_FLYASH", "Halfton Fly Ash"),
                    ("CRUSHED_HALFTON", "Crushed Stone Halfton"),
                    ("BHARRAN_HYVA", "Bharran Hyva"),
                    ("BHARRAN_HALFTON", "Bharran Halfton"),
                ],
                default="",
                help_text="Hyva load type — sets the per-trip rate automatically",
                max_length=20,
            ),
        ),
    ]
