# Generated by Django 6.1 on 2026-09-14 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("labour", "0017_alter_labourtripgroup_load_type"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="labouradvance",
            index=models.Index(
                fields=["labour", "date"], name="labour_labo_labour__fa75a6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="labourdriverpayment",
            index=models.Index(
                fields=["labour", "period_start"], name="labour_labo_labour__e638f5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="labourextrapayment",
            index=models.Index(
                fields=["labour", "date"], name="labour_labo_labour__e08e82_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="labourrozi",
            index=models.Index(
                fields=["labour", "date"], name="labour_labo_labour__cdf616_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="laboursettlement",
            index=models.Index(
                fields=["labour", "settlement_date"],
                name="labour_labo_labour__59d361_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="labourtripgroup",
            index=models.Index(fields=["date"], name="labour_labo_date_79d9f9_idx"),
        ),
    ]
