# Generated by Django 6.1 on 2026-09-21 12:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("labour", "0018_labouradvance_labour_labo_labour__fa75a6_idx_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="labour",
            name="user",
            field=models.OneToOneField(
                blank=True,
                help_text="Linked login for restricted operator mode — operator sees only his own page",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="operator_labour",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
