# Generated by Django 6.1 on 2026-10-04 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("labour", "0020_labourholiday"),
    ]

    operations = [
        migrations.AddField(
            model_name="labour",
            name="is_one_day",
            field=models.BooleanField(
                default=False,
                help_text="One-day driver via Trips quick-add. Hidden from Labour section (lists, counts, pickers); lives only in Trips.",
            ),
        ),
    ]
