# Generated by Django 6.1 on 2026-08-17 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="opening_balance",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Starting outstanding amount for this customer (editable anytime).",
                max_digits=15,
            ),
        ),
    ]
