# Generated by Django 6.1 on 2026-08-17 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0002_customer_opening_balance"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="is_vendor",
            field=models.BooleanField(
                default=False,
                help_text="Check if party is also a Material Supplier/Vendor (Dual-role).",
            ),
        ),
    ]
