# Generated by Django 6.1 on 2026-08-26 05:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vehicles", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="VehicleDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "doc_type",
                    models.CharField(
                        choices=[
                            ("PUC", "PUC Certificate"),
                            ("INSURANCE", "Insurance"),
                            ("FITNESS", "Fitness Certificate"),
                            ("PERMIT", "Permit"),
                            ("RC", "RC Book"),
                            ("TAX", "Road Tax"),
                            ("OTHER", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "document_number",
                    models.CharField(
                        blank=True,
                        help_text="Policy/Certificate number (optional)",
                        max_length=100,
                    ),
                ),
                ("issue_date", models.DateField(blank=True, null=True)),
                ("expiry_date", models.DateField(db_index=True)),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        help_text="PDF/Photo upload (optional)",
                        null=True,
                        upload_to="vehicle_docs/",
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("notified_30", models.BooleanField(default=False)),
                ("notified_15", models.BooleanField(default=False)),
                ("notified_7", models.BooleanField(default=False)),
                ("notified_expired", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="vehicles.vehicle",
                    ),
                ),
            ],
            options={
                "ordering": ["expiry_date", "id"],
            },
        ),
    ]
