# Generated by Django 6.1 on 2026-08-26 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vehicles", "0002_vehicledocument"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehicledocument",
            name="doc_type",
            field=models.CharField(
                choices=[
                    ("PUC", "PUC Certificate"),
                    ("INSURANCE", "Insurance"),
                    ("FITNESS", "Fitness Certificate"),
                    ("PERMIT", "Permit"),
                    ("RC", "RC Book"),
                    ("TAX", "Road Tax"),
                    ("ENV_TAX", "Environment Tax"),
                    ("MV_TAX", "MV Tax"),
                    ("OTHER", "Other"),
                ],
                max_length=20,
            ),
        ),
    ]
