# Generated by Django 6.1 on 2026-08-10 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("master_data", "0002_paymentmethod_alter_role_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="LabourType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=50, unique=True)),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "payment_basis",
                    models.CharField(
                        choices=[
                            ("DAILY", "Daily"),
                            ("MONTHLY", "Monthly"),
                            ("PER_ENTRY", "Per Entry"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AlterModelOptions(
            name="role",
            options={"ordering": ["name"]},
        ),
    ]
