# Generated by Django 6.1 on 2026-08-10 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("master_data", "0007_customertype"),
    ]

    operations = [
        migrations.CreateModel(
            name="Material",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=50, unique=True)),
                ("name", models.CharField(max_length=150, unique=True)),
                (
                    "unit",
                    models.CharField(
                        choices=[("TRIP", "Trip"), ("PIECE", "Piece")], max_length=20
                    ),
                ),
                ("gst_applicable", models.BooleanField(default=False)),
                (
                    "gst_rate",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
