# Generated by Django 6.1 on 2026-08-11 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("trips", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="trip",
            old_name="rate_per_unit",
            new_name="rate",
        ),
    ]
