# Generated by Django 6.1 on 2026-08-11 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("labour", "0007_laboursalaryperiod"),
        ("trips", "0003_trippayment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="trip",
            name="driver",
        ),
        migrations.AddField(
            model_name="trip",
            name="destination",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="trip",
            name="drivers",
            field=models.ManyToManyField(
                blank=True, related_name="trips_driven", to="labour.labour"
            ),
        ),
    ]
