# Generated by Django 6.1 on 2026-08-11 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trips", "0004_remove_trip_driver_trip_destination_trip_drivers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trip",
            name="trip_code",
            field=models.CharField(
                blank=True, editable=False, max_length=30, unique=True
            ),
        ),
    ]
