# Generated by Django 6.1 on 2026-08-14 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0001_initial"),
        ("master_data", "0008_material"),
        ("trips", "0005_alter_trip_trip_code"),
        ("vehicles", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="trip",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("CUSTOMER_DELIVERY", "Customer Delivery"),
                    ("INTERNAL_STOCK", "Internal Stock"),
                ],
                default="CUSTOMER_DELIVERY",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="trip",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="trips",
                to="customers.customer",
            ),
        ),
        migrations.AlterField(
            model_name="trip",
            name="vehicle",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="trips",
                to="vehicles.vehicle",
            ),
        ),
        migrations.AlterField(
            model_name="trippayment",
            name="payment_method",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="trip_payments",
                to="master_data.paymentmethod",
            ),
        ),
    ]
