# Generated by Django 6.1 on 2026-08-14 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trips", "0006_trip_transaction_type_alter_trip_customer_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="trippayment",
            name="payment_code",
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
    ]
