# Generated by Django 6.1 on 2026-08-14 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trips", "0007_trippayment_payment_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trippayment",
            name="payment_code",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
