# Generated by Django 6.1 on 2026-08-14 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trips", "0008_alter_trippayment_payment_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trippayment",
            name="payment_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
