# Generated by Django 6.1 on 2026-08-17 07:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0002_customer_opening_balance"),
        ("trips", "0009_alter_trippayment_payment_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="trippayment",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payments",
                to="customers.customer",
            ),
        ),
        migrations.AlterField(
            model_name="trippayment",
            name="trip",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payments",
                to="trips.trip",
            ),
        ),
    ]
