# Generated by Django 6.1 on 2026-08-17 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trips", "0010_trippayment_customer_alter_trippayment_trip"),
    ]

    operations = [
        migrations.AddField(
            model_name="trip",
            name="driver_trip_counts",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Stores trip counts completed per driver, e.g. {'18': 3, '6': 2}",
            ),
        ),
    ]
