# Generated by Django 6.1 on 2026-08-17 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trips", "0011_trip_driver_trip_counts"),
    ]

    operations = [
        migrations.AddField(
            model_name="trippayment",
            name="payment_type",
            field=models.CharField(
                choices=[
                    ("RECEIVED", "Payment Received from Customer"),
                    ("PAID", "Payment Paid to Vendor/Customer"),
                    ("CONTRA", "Contra Settlement (Netting Off)"),
                ],
                default="RECEIVED",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="trip",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("CUSTOMER_DELIVERY", "Customer Delivery (Outward)"),
                    ("VENDOR_SUPPLY", "Vendor/Supplier Material (Inward)"),
                    ("INTERNAL_STOCK", "Internal Stock"),
                ],
                default="CUSTOMER_DELIVERY",
                max_length=20,
            ),
        ),
    ]
