# Generated by Django 6.1 on 2026-08-17 16:39

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trips", "0012_trippayment_payment_type_alter_trip_transaction_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="trip",
            name="driver_bhatta",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=Decimal("200.00"),
                help_text="Fixed Driver Bhatta Allowance (Default ₹200.00)",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="trip",
            name="end_reading",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="JCB Hour Meter Ending Reading (e.g. 1235.1)",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="trip",
            name="start_reading",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="JCB Hour Meter Starting Reading (e.g. 1233.2)",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="trip",
            name="total_hours",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Total Hours Worked = End Reading - Start Reading",
                max_digits=10,
                null=True,
            ),
        ),
    ]
