# Generated by Django 6.1 on 2026-08-17 18:43

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("master_data", "0008_material"),
        ("trips", "0013_trip_driver_bhatta_trip_end_reading_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trip",
            name="driver_bhatta",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Driver Bhatta Allowance (Applicable for JCB trips, Default ₹200.00 for JCB)",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="trip",
            name="material",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="trips",
                to="master_data.material",
            ),
        ),
    ]
