# Generated by Django 6.1 on 2026-08-22 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trips", "0014_alter_trip_driver_bhatta_alter_trip_material"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trip",
            name="trip_date",
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name="trippayment",
            name="payment_date",
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
    ]
