# Generated by Django 6.1 on 2026-08-25 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trips", "0016_backfill_payment_dates"),
    ]

    operations = [
        migrations.AddField(
            model_name="trip",
            name="linked_inward_trip",
            field=models.ForeignKey(
                blank=True,
                help_text="VENDOR_SUPPLY inward trip jisse ye outward bana",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="linked_outward_trips",
                to="trips.trip",
            ),
        ),
    ]
